server:
  port: 9000
spring:
  profiles:
    active: dev

  application:
    name: blog-system
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mail:
    host: smtp.163.com
    password: ZJHLBXHNHITCHUAG
    username: twbat_lee@163.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          debug: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false
logging:
  file:
    path: /log/system

blog.secret: awascdfmblsJsdmMWjNSFxsflGsdmKDFHsdnJNFSL
blog.out.day: 7
blog.extend.expiration: 5
